### ISSUE TITLE
xbmc.gui version error

### ISSUE THREAD

**Issue by Elrau** [scott967/Aeon_MQ5_Mod_Matrix#1]
Hi,

With Matrix 19.0.0 I can't add the zip file for Matrix, i get this error : "The dependency for xbmc.gui in version 5.14.0 could not be resolved".

Is there something else to do I didn't see in README ?

Regards,

**Comment by Elrau** [comment]
I had to get repository zip first and uninstall add-on I already add.

Repo for people in need:
https://github.com/scott967/repo-Aeon_MQ5_Mod/releases/tag/11.0.0

**Comment by scott967** [comment]
If you directly download just the skin zip, ensure you get the release ver which as of writing is 11.1.0 and is equal to master branch.  The dependency on xbmc gui should be 5.15.0 (has been for almost a year).

I always recommend getting my repo and installing the skin from there, due to the number of addons that aren't in the kodi repo for Matrix due to the python3 requirement.  I did my best to update those addons to py3 and also made Matrix Kodi changes where necessary, but I'm not an expert on all the functions in the addons.

As of this writing there is also a development branch of the skin 11.1.1 and my plan is to have a single dev branch and merge that into master when testing is done with the bumped version number.

Also, currently the skin will work in Kodi 20 (N) nightlies as no skin changes are needed at this early stage.  When the time comes that Kodi 20 diverges a new github repo will be created for it.
